#!/usr/bin/env bash
# =============================================================================
# build-crossplane-plugin.sh
#
# Fetches the headlamp-plugin-crossplane source from its remote repository,
# builds it, and writes a Kubernetes ConfigMap manifest
# (configmap-crossplane-plugin.yaml) in the root of this repo so it can be
# applied to the cluster.
#
# Usage:
#   ./scripts/build-crossplane-plugin.sh
#
# Requirements:
#   - git, node, npm (Node LTS recommended)
#
# TODO: Once headlamp-plugin-crossplane is published to ArtifactHub / npm,
#       replace this script with a pluginsManager entry in values.yaml (same
#       pattern as headlamp-flux).  The ConfigMap approach is a stop-gap for
#       local dev.
# =============================================================================

set -euo pipefail

REPO_URL="https://github.tools.sap/openmcp/headlamp-plugin-crossplane.git"
WORK_DIR="$(mktemp -d)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT_FILE="${REPO_ROOT}/configmap-crossplane-plugin.yaml"

echo "==> Cloning headlamp-plugin-crossplane into ${WORK_DIR} ..."
git clone --depth 1 "${REPO_URL}" "${WORK_DIR}/headlamp-plugin-crossplane"

echo "==> Installing dependencies ..."
npm --prefix "${WORK_DIR}/headlamp-plugin-crossplane" ci

echo "==> Building plugin ..."
npm --prefix "${WORK_DIR}/headlamp-plugin-crossplane" run build

MAIN_JS="${WORK_DIR}/headlamp-plugin-crossplane/dist/main.js"
PACKAGE_JSON="${WORK_DIR}/headlamp-plugin-crossplane/package.json"

if [[ ! -f "${MAIN_JS}" ]]; then
  echo "ERROR: Build did not produce dist/main.js" >&2
  exit 1
fi

echo "==> Reading plugin metadata ..."
PLUGIN_NAME=$(node -e "process.stdout.write(require('${PACKAGE_JSON}').name)")
PLUGIN_VERSION=$(node -e "process.stdout.write(require('${PACKAGE_JSON}').version)")

# Extract the fields Headlamp needs at runtime.
# devDependencies MUST be included: Headlamp checks
# devDependencies["@kinvolk/headlamp-plugin"] >= "0.8.0-alpha.3" to
# decide whether a plugin is compatible. Omitting it causes the plugin
# to be silently disabled with "Incompatible plugins disabled" warning.
PACKAGE_JSON_CONTENT=$(node -e "
const p = require('${PACKAGE_JSON}');
process.stdout.write(JSON.stringify({name: p.name, version: p.version, devDependencies: p.devDependencies}));
")

echo "==> Generating ConfigMap for ${PLUGIN_NAME}@${PLUGIN_VERSION} ..."

# Indent every line of main.js by 4 spaces for the YAML literal block scalar
MAIN_JS_INDENTED=$(sed 's/^/    /' "${MAIN_JS}")

cat > "${OUTPUT_FILE}" << YAML
# This file is auto-generated by scripts/build-crossplane-plugin.sh — do not edit by hand.
# Plugin: ${PLUGIN_NAME} v${PLUGIN_VERSION}
# Source: ${REPO_URL}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crossplane-plugin
  namespace: headlamp
data:
  package.json: |-
    ${PACKAGE_JSON_CONTENT}
  main.js: |-
${MAIN_JS_INDENTED}
YAML

echo "==> Cleaning up temp directory ..."
rm -rf "${WORK_DIR}"

echo ""
echo "Done! Written to: ${OUTPUT_FILE}"
echo ""
echo "Apply with:"
echo "  kubectl apply -f ${OUTPUT_FILE}"
echo "  helm upgrade --install headlamp . -n headlamp"
