name: Release

on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: "Helm chart version in semver format e.g. 0.1.0"
        required: true

# base permissions for all jobs should be minimal
permissions:
  contents: read

jobs:
  release:
    name: Publish Helm chart to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Check if tag already exists
        run: |
          if git rev-parse v${{ github.event.inputs.nextVersion }} >/dev/null 2>&1
          then
            echo "Tag v${{ github.event.inputs.nextVersion }} already exists."
            exit 1
          else
            echo "Tag does not exist. Building release version ${{ github.event.inputs.nextVersion }}"
          fi

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build chart dependencies
        run: helm dependency update

      - name: Package chart
        run: helm package . --version ${{ github.event.inputs.nextVersion }}

      - name: Push OCI image to GHCR
        run: |
          helm push headlamp-deployment-${{ github.event.inputs.nextVersion }}.tgz \
            oci://ghcr.io/${{ github.repository_owner }}/helm-charts

      - name: Create Release with autogenerated release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.nextVersion }} \
            --generate-notes \
            --target ${{ github.sha }} \
            headlamp-deployment-${{ github.event.inputs.nextVersion }}.tgz
